name: Build

on:
  pull_request_target:
    branches:
      main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

          # - name: BrowserStack env setup
          #   uses: browserstack/github-actions/setup-env@master
          #   with:
          #     username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          #     access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

          # - name: 'BrowserStack local tunnel setup'
          #   uses: browserstack/github-actions/setup-local@master
          #   with:
          #     local-testing: start
          #     local-identifier: random

          # - name: Run BrowserStack tests
          #     env:
          #       PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          #     run: |
          #       set -xeuo pipefail
          #       yarn serve &
          #       sleep 10
          #       yarn test-percy -e default,firefox,edge,safari -o reports 2>&1 | tee bslog.txt

          # - name: Get Percy URL
          #   id: percy_url
          #   run: |
          #     URL=$(grep "percy.io" bslog.txt | awk '{print $NF}')
          #     echo "Event type: ${{ github.event_name }}"
          #     echo "Percy URL: $URL"
          #     echo url=$URL >> $GITHUB_OUTPUT

          # - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
          #   uses: browserstack/github-actions/setup-local@master
          #   with:
          #     local-testing: stop
          #

  # comment:
  #   if: ${{ (github.event_name == 'pull_request') || (github.event_name == 'pull_request_target') }}
  #   needs: [build]
  #   permissions:
  #     pull-requests: write
  #   uses: cosmicds/carina/.github/workflows/pr-comment.yml@main
  #   with:
  #     comment: "Percy diffs for commit ${{ github.event.pull_request.head.sha }} can be found at ${{ needs.build.outputs.percy_url }}"
